### ISSUE TITLE
Review, Phase 1

### ISSUE THREAD

**Issue by vr8hub** [PiperKev/richard-henry-dana-jr_two-years-before-the-mast#1]
There's a lot here, including your 230+(!) editorial commits changing compound words (see below), so I'm going to do this in phases. This is Phase 1; I'll let you work on this list and then continue on when you're finished with this.

- [ ] There are several words with unsemanticated italics that need to be semanticated, e.g. ante, ex officio, etc.
- [ ] There are several words tagged with language that are in M-W and so should not be (SEMoS [8.2.9.4](https://standardebooks.org/manual/1.7.1/single-page#8.2.9.4)), e.g. sombrero, siesta, etc.
- [ ] Likewise, there are several words marked as emphasis that are not emphasis, e.g. "i.e.," (which should not be italicized at all), Mahon soger (the endnote would indicate it's Turkish?), Prisidio, paseo, café noir, etc. 
- [ ] There are multiple instances of an endnote being wholly contained by another tag, e.g. `<i>sometext<a href="…"></a></i>`; the endnote should be outside the other tag, e.g. `<i>sometext</i><a href="…"></a>`.
- [ ] Instances of negro* should be capitalized (editorial).
- [ ] There are inconsistencies in some of the book and ship names, e.g. _Mariner's Sketches_ and _Mariners' Sketches_, _Ann M'Kim_ and _Ann McKim_, etc. We should probably standardize them, editorial. (See SEMoS [7.5.3.2](https://standardebooks.org/manual/1.7.1/single-page#8.7.5.3.2) for the latter.)
- [ ] Poems are only italicized if they're book-length, e.g. _Iliad_, _Aenid_, etc. Some of the poems so marked are not book-length, e.g. “Ille et nefasto” (which is correctly quoted in the endnotes, but italicized in the text).
- [ ] Identical elements in CSS should be combined, like sender/recipient/salutation/signature are combined in the letter section. Thus, each of the identical song and verse elements should be combined.
- [ ] The blockquote:nth-of-type(4) CSS needs the section id on it (as it is, it's a general CSS that would cover _any_ fourth blockquote. You're only targeting (I assume) a specific fourth blockquote in a particular chapter, e.g. #chapter-N blockquote:nth-of-type(4)…
- [ ] There are instances of untagged name initials, e.g. (at least) J. S. T. Coolidge in the endnotes. These need the appropriate abbreviation tag.
- [ ] I'm not sure why the transcription has text with the chapter header when neither of the scans you're using do (well, the second one does, but it doesn't match what's in the transcription), but if they're to be kept they would appear to be bridgeheads, not chapter titles. Multiple short descriptions separated by em-dashes are almost always bridgeheads. See SEMoS [7.2.11](https://standardebooks.org/manual/1.7.1/single-page#7.2.11) for formatting and CSS.
- [ ] If the change from 166 to 116º is going to be kept, it should be documented somewhere _why_ the change was made, e.g. in the production notes.
- [ ] Capitán is accented in Spanish. So is pulpería: pulperia is in M-W's unabridged, but that doesn't count (SEMoS [8.2.9.4](https://standardebooks.org/manual/1.7.1/single-page#8.2.9.4)), so it's treated as Spanish and the accent is kept (and it's tagged).
- [ ] Bucketmaker, winemaking are not in M-W; wood cutting is woodcutting, Liberty men is Libertymen. (For this and many other reasons, we generally do not mess with compound words other than what modernize spelling does. It's something of a time suck, both for the producer and reviewer, who has to review every one of the changes; the 230+ here took longer than a normal review to check by themselves.)
- [ ] There is a single day (July 22nd.) where the period is treated as part of the nd and made into an abbreviation. That would appear to be a mistake?
- [ ] Using chapters for the "ante"s in the final chapter is much less specific than the page numbers given in the book. Let's put ID's on the first paragraph being referred to and link to that, probably with something like "see here" or something similar. (Since it's names being referred to, it's relatively easy to identify the paragraph in question; you can target the date paragraph, or the paragraph that first mentions the name.)
- [ ] There is at least one thematic break missing (ch. 38, "It is time my fellow…"); might there be others?
- [ ] When an entire blockquote is non-English, the language tag goes on the blockquote, not on the lines. Note this requires additional CSS (SEMoS [8.2.9.6](https://standardebooks.org/manual/1.7.1/single-page#8.2.9.6)).
- [ ] Ch. 20 has Wed, 7/18 as one date and Sat, 7/11 as the next. Not only is 7/11 prior to 7/18 (instead of following), 7/18 and 7/11 are exactly one week apart, so cannot be two different days. I found an [edition on IA](https://archive.org/details/twoyearsbeforema00dana2/page/202/mode/2up) that changes the first entry to 7/8, which is obviously correct. I think that's worth changing (and a production note).
- [ ] Ch. 36 has "17t" instead of "17th".
- [ ] The removal of the em-dashes in 48bd472 is to match the scans, so is not Editorial.
- [ ] Likewise the change from nautice to nauticé (I'm also curious what that word is; the only thing that turns up in a search is this book.)
- [ ] For the instances of where the comma was moved outside the parens, I don't think the prior comma is needed. Thus, "… the mate, (as I was told), …" is one too many commas; it should be "… the mate (as I was told), …". That's what _I_ would do, but I'll check with Alex to make sure; he probably won't. :)
- [ ] Nothing to do this time, but just a note for the future: we want the commit message to tell us what happened and preferably everything that happened. Thus, "Correct chapter-X" doesn't really tell us anything. ("Proofreading corrections for chapter-X" is also fairly generic, but at least tells us what the contents of the commit are.) "Fix preface" _also_ contained a rebuild of the ToC ("Fix preface, rebuild ToC"), and so on.
