### ISSUE TITLE
Review, Phase 2

### ISSUE THREAD

**Issue by vr8hub** [PiperKev/richard-henry-dana-jr_two-years-before-the-mast#2]
- [x] `se clean` makes changes that should be accepted.
- [x] So does `typogrify`. These (and lint) should always be run the _last thing_ before submitting. Yes, I have to remind myself of this on every book. :)
- [x] Since note 164 is referring to sounds, I believe those should be phonemes, not graphemes.
- [x] There are a number of instances of semi-colons inside quotes that are not ending dialog (see SEMoS [8.7.2.1](https://standardebooks.org/manual/1.7.1/single-page#8.7.2.1)), so should be moved outside.
- [x] I'm not sure the _Leese_ in note-282 needs unsemanticated italics, or italics at all. We'll leave it and see what Alex does and maybe both learn something. :)
- [x] Bridgeheads are sentence-cased within the clauses; see SEMoS [7.2.11.4](https://standardebooks.org/manual/1.7.1/single-page#7.2.11.4).
- [x] When a letter has a header, the recipient goes in it, SEMoS [7.7.2.1](https://standardebooks.org/manual/1.7.1/single-page#7.7.2.1), if it's at the top. (It would go in the footer if it were at the bottom.)
- [x] Bridgeheads are only for chapter headers; for the last log entry in ch. 38, it can be just a regular header, which can then be targeted in CSS to format it (it doesn't need the 60% restriction since it's not a bridgehead). It doesn't need dateline characteristics, either, as that's for letters, se._letter_.dateline :)
- [x] The first occurrence of Alabama in ch. 38 is not tagged.
- [x] The comma after Dear Sir in the letter in ch. 38 should be removed. Typogrify removes commas in instances of `,—`, but the `</span>` here kept it from being found.
- [x] The N.N.E. in ch. 7 needs spaces.
- [x] The 22nd. that had the abbreviation now is the only one that has the period inside the closing italic. But based on our normal guidelines (8.2.5) they should all be inside, since in each case the entire clause is being italicized.
- [x] Proper names are not italicized (once again, [8.2.9.2](https://standardebooks.org/manual/1.7.1/single-page#8.2.9.2)), so, e.g., "Ille et nefasto" should not be tagged, and any others that were done.
- [x] Horace's _Odes_ isn't a poem, it's a _book_ of poems, and should be tagged appropriately. (The scans have this correct—the poem is quoted, the book is italicized.)
- [x] Non-grammatical periods following roman numerals are removed, SEMoS [8.8.5](https://standardebooks.org/manual/1.7.1/single-page#8.8.5).
- [x] Periods aren't needed after "see here," either; it isn't a sentence or abbreviation.
- [x] I don't think we need the "ante's" either; it means "before," which indicates the footnote is prior to this page, but since there are no pages in an ebook, the link is sufficient to tell the reader the location.
- [x] Biblical references are modernized, see SEMoS [8.17.4](https://standardebooks.org/manual/1.7.1/single-page#8.17.4).
- [x] There are a number of abbreviations that have "eoc" on them that are not end-of-clause, see SEMoS [8.10.3](https://standardebooks.org/manual/1.7.1/single-page#8.10.3).
- [x] The Esq. abbreviation tag in ch. 38 includes the trailing comma, which it should not.
- [x] The dash in Moku—Nui Moku is an em-dash in the text, an en-dash in the endnote. It should be the former in both places.
- [x] There are a number of non-English phrases that are tagged with span instead of italics. Why? If they're not in M-W, then they're italicized, unless they're proper names/titles. (Once again, SEMoS 8.2.) When spans are used, they're only when pronunciation help is needed.
- [x] Note 49 begins with a double-quote and ends with a single one.
- [x] The "40 fathoms" in ch. 7 is subject to SEMoS [8.8.3](https://standardebooks.org/manual/1.7.1/single-page#8.8.3).
- [x] The production notes need a "The" in front of "SE edition".
- [x] What is the "iaw" in the production notes? If it's an abbreviation, it should probably be expanded, since I have no idea what it means and I assume others won't either. :)
- [x] I believe Pilgrim should be italicized (not tagged) in the long description.
- [x] I think I would reverse the 2nd and 3rd paragraphs of the long description? The first and last are about the book, the second about the particular edition. The two about the book should probably stay together.

**Comment by vr8hub** [comment]
- [ ] Part of the semi-colon commit (e9ddece) changed "Parting moments" (plural) to "Parting moment" (singular) in ch. 13. It's plural in the scans.
- [ ] _Alert_ needs a ship tag in ch. 22's bridgehead. This means you also need the additional CSS in the manual for the bridgehead to handle italics.
- [ ] I believe the Sunday wash-Up should be wash-up in ch. 27's bridgehead.
- [ ] I think I know why you put a span on Capitán and Maestro, but in these two cases we're dealing with a _phrase_, and we semanticate the phrase as a whole. Either it's _all_ a proper name/title, or it's all a non-English phrase. I think in these cases we can call them a non-English phrase, and italicize the whole thing.
- [ ] Sorry, I just noticed that semantics are missing from the defined terms in the endnotes. E.g., “Gil Blas” is quoted rather than tagged in 209, Maestro de la casa isn't tagged in 220, Auctoritate mihi commissa in 227, etc. They're already italicized by the dfn, yes, but they still need their appropriate semantics. In looking at the corpus, there are other instances of the tags being on the `dfn`s themselves, so I think you can do the same, e.g. `<dfn xml:lang="es">` rather than `<dfn><i xml:lang="es">`, etc.
- [ ] I just happened to see a "under weigh" while I was looking at something else. The ngram support for that is nonexistent now, so I think it should be modernized to "underway," but I've asked Alex on the list to be sure.
- [ ] The clairvoyance in ch. 28 doesn't feel like emphasis, more that it was non-English (at the time). Up to you, though—if you feel it is emphasis, then leave it.
- [ ] A few sentences later, there is a "… ending with W., )". First, there should be no space before the paren, and second, the comma goes outside the paren.
- [ ] The A.B. abbreviation should have a academic tag, not initialism; see SEMoS [8.10.5](https://standardebooks.org/manual/1.7.1/single-page#8.10.5).
- [ ] When you removed the bridgehead semantic from the last log entry, you didn't add CSS to italicize it. Also, _Alert_ should be tagged there as well. (All ships should be tagged everywhere they occur. Well, except the already noted exception of the long description, but even there they should be italicized.)
- [ ] There are still several sets of initials that have "eoc" on their tag that are not eoc.
- [ ] You removed the comma after Esq. completely; just want to make sure you understood that I said it should be removed from _the abbreviation tag_, not completely. If you want to remove it completely, that's up to you. :)
- [ ] Sorry again, I just noticed that the name of the book is in quotes in the long description instead of italics. Book names are always italicized.

OK, sorry, we have out-of-town company that just got in, so I have to take a break. I don't _think_ there's much of anything left, but I'll take another look after everyone goes to bed and you've had a chance to do these.

**Comment by vr8hub** [comment]
As you probably saw on the list, Alex approved under weigh -> underway.

**Comment by vr8hub** [comment]
- [ ] I referred you to the SEMoS 8.10.3 in the first issue above about the "eoc"s, so that you could read and understand what the rule said and what that meant for the text. In the followup, I specifically said there were several _sets of _**initials**__ that still have an invalid "eoc". But what was done was to remove the "eoc"s from almost everything _except_ the initials, i.e. from the things that 8.10.3 specifically says _does_ need the "eoc"s. Thus, that commit (8e93307) needs to be reverted and the actual problem (the _initials_ that are not end-of-clause that have "eoc" on them) corrected.
- [ ] The book should always be reviewed after any changes are made, to ensure the changes were correct, and that there no unintended side effects. The new CSS for ch. 38 header changes _all_ of the headers in ch. 38, because the selector was just `#chapter-38 blockquote header`. Notice the difference between that and the already-existing selector: `#chapter-38 blockquote:nth-of-type(4) header`? The former says _all_ blockquotes in #chapter-38, the latter says just the fourth blockquote (i.e. the letter). My email specifically said it was _example_ CSS, since I didn't know how you targeted the header. Since there was already CSS to handle the header italics, the only thing that was needed was to handle another italic _inside_ that one. Also, as elsewhere, the italics for the first and last paragraph elements can be combined, since the entire header is to be italicized.
````
#chapter-38 blockquote:nth-of-type(4) header{
  font-style: italic;
}

#chapter-38 blockquote:nth-of-type(4) header i{
  font-style: normal;
}

#chapter-38 blockquote:nth-of-type(4) header p:last-child{
  text-align: right;
}
````
Once those are corrected I believe that's it!
